'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cooperative1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, Address = &apos;.
        '''</summary>
        Friend ReadOnly Property _Address() As String
            Get
                Return ResourceManager.GetString("_Address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, Age = &apos;.
        '''</summary>
        Friend ReadOnly Property _Age() As String
            Get
                Return ResourceManager.GetString("_Age", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos; AND Password = &apos;.
        '''</summary>
        Friend ReadOnly Property _AND_Password() As String
            Get
                Return ResourceManager.GetString("_AND_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, [Date of Birth] = &apos;.
        '''</summary>
        Friend ReadOnly Property _Date_of_Birth() As String
            Get
                Return ResourceManager.GetString("_Date_of_Birth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, [Date of Membership] = &apos;.
        '''</summary>
        Friend ReadOnly Property _Date_of_Membership() As String
            Get
                Return ResourceManager.GetString("_Date_of_Membership", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, Department = &apos;.
        '''</summary>
        Friend ReadOnly Property _Department() As String
            Get
                Return ResourceManager.GetString("_Department", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property _Exit() As String
            Get
                Return ResourceManager.GetString("Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [First Name].
        '''</summary>
        Friend ReadOnly Property _First_Name() As String
            Get
                Return ResourceManager.GetString("_First_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, [First Name] = &apos;.
        '''</summary>
        Friend ReadOnly Property _First_Name0() As String
            Get
                Return ResourceManager.GetString("_First_Name0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, Gender = &apos;.
        '''</summary>
        Friend ReadOnly Property _Gender() As String
            Get
                Return ResourceManager.GetString("_Gender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [ID Card].
        '''</summary>
        Friend ReadOnly Property _ID_Card() As String
            Get
                Return ResourceManager.GetString("_ID_Card", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, Investment = &apos;.
        '''</summary>
        Friend ReadOnly Property _Investment() As String
            Get
                Return ResourceManager.GetString("_Investment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Last Name].
        '''</summary>
        Friend ReadOnly Property _Last_Name() As String
            Get
                Return ResourceManager.GetString("_Last_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, [Last Name] = &apos;.
        '''</summary>
        Friend ReadOnly Property _Last_Name0() As String
            Get
                Return ResourceManager.GetString("_Last_Name0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Member ID].
        '''</summary>
        Friend ReadOnly Property _Member_ID() As String
            Get
                Return ResourceManager.GetString("_Member_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Number of shares].
        '''</summary>
        Friend ReadOnly Property _Number_of_shares() As String
            Get
                Return ResourceManager.GetString("_Number_of_shares", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, [Number of shares] = &apos;.
        '''</summary>
        Friend ReadOnly Property _Number_of_shares0() As String
            Get
                Return ResourceManager.GetString("_Number_of_shares0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %&apos; OR [First Name] LIKE &apos;%.
        '''</summary>
        Friend ReadOnly Property _OR_First_Name_LIKE() As String
            Get
                Return ResourceManager.GetString("_OR_First_Name_LIKE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %&apos; OR [ID Card] LIKE &apos;%.
        '''</summary>
        Friend ReadOnly Property _OR_ID_Card_LIKE() As String
            Get
                Return ResourceManager.GetString("_OR_ID_Card_LIKE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %&apos; OR [Last Name] LIKE &apos;%.
        '''</summary>
        Friend ReadOnly Property _OR_Last_Name_LIKE() As String
            Get
                Return ResourceManager.GetString("_OR_Last_Name_LIKE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, Tel = &apos;.
        '''</summary>
        Friend ReadOnly Property _Tel() As String
            Get
                Return ResourceManager.GetString("_Tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos; WHERE [Member ID] = &apos;.
        '''</summary>
        Friend ReadOnly Property _WHERE_Member_ID() As String
            Get
                Return ResourceManager.GetString("_WHERE_Member_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend ReadOnly Property Address() As String
            Get
                Return ResourceManager.GetString("Address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Age.
        '''</summary>
        Friend ReadOnly Property Age() As String
            Get
                Return ResourceManager.GetString("Age", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aleart.
        '''</summary>
        Friend ReadOnly Property Aleart() As String
            Get
                Return ResourceManager.GetString("Aleart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alert.
        '''</summary>
        Friend ReadOnly Property Alert() As String
            Get
                Return ResourceManager.GetString("Alert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_form_close_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_form_close-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arial.
        '''</summary>
        Friend ReadOnly Property Arial() As String
            Get
                Return ResourceManager.GetString("Arial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmation.
        '''</summary>
        Friend ReadOnly Property Confirmation() As String
            Get
                Return ResourceManager.GetString("Confirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Birth.
        '''</summary>
        Friend ReadOnly Property Date_of_Birth() As String
            Get
                Return ResourceManager.GetString("Date_of_Birth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Membership.
        '''</summary>
        Friend ReadOnly Property Date_of_Membership() As String
            Get
                Return ResourceManager.GetString("Date_of_Membership", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dd-MM-yyyy.
        '''</summary>
        Friend ReadOnly Property dd_MM_yyyy() As String
            Get
                Return ResourceManager.GetString("dd_MM_yyyy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dd/MM/yyyy.
        '''</summary>
        Friend ReadOnly Property dd_MM_yyyy0() As String
            Get
                Return ResourceManager.GetString("dd_MM_yyyy0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM Member WHERE [Member ID] = &apos;.
        '''</summary>
        Friend ReadOnly Property DELETE_FROM_Member_WHERE_Membe() As String
            Get
                Return ResourceManager.GetString("DELETE_FROM_Member_WHERE_Membe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Department.
        '''</summary>
        Friend ReadOnly Property Department() As String
            Get
                Return ResourceManager.GetString("Department", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to Add?.
        '''</summary>
        Friend ReadOnly Property Do_you_want_to_Add() As String
            Get
                Return ResourceManager.GetString("Do_you_want_to_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to Delete?.
        '''</summary>
        Friend ReadOnly Property Do_you_want_to_Delete() As String
            Get
                Return ResourceManager.GetString("Do_you_want_to_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to Update?.
        '''</summary>
        Friend ReadOnly Property Do_you_want_to_Update() As String
            Get
                Return ResourceManager.GetString("Do_you_want_to_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dsn=Cooperative_DB;uid=sa;pwd=sa.
        '''</summary>
        Friend ReadOnly Property Dsn_Cooperative_DB_uid_sa_pwd_() As String
            Get
                Return ResourceManager.GetString("Dsn_Cooperative_DB_uid_sa_pwd_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dsn=Cooperative_DB;uid=sa;pwd=sa;.
        '''</summary>
        Friend ReadOnly Property Dsn_Cooperative_DB_uid_sa_pwd_0() As String
            Get
                Return ResourceManager.GetString("Dsn_Cooperative_DB_uid_sa_pwd_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit application?.
        '''</summary>
        Friend ReadOnly Property Exit_application() As String
            Get
                Return ResourceManager.GetString("Exit_application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Friend ReadOnly Property First_Name() As String
            Get
                Return ResourceManager.GetString("First_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gender.
        '''</summary>
        Friend ReadOnly Property Gender() As String
            Get
                Return ResourceManager.GetString("Gender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID Card.
        '''</summary>
        Friend ReadOnly Property ID_Card() As String
            Get
                Return ResourceManager.GetString("ID_Card", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID Card does not exist. Please check again..
        '''</summary>
        Friend ReadOnly Property ID_Card_does_not_exist_Please_() As String
            Get
                Return ResourceManager.GetString("ID_Card_does_not_exist_Please_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Member ([Member ID], [ID Card], [First Name], [Last Name], Gender, [Date of Birth], Age, Address, Tel, Investment, [Number of shares], Department, [Date of Membership]) VALUES (&apos;.
        '''</summary>
        Friend ReadOnly Property INSERT_INTO_Member_Member_ID_I() As String
            Get
                Return ResourceManager.GetString("INSERT_INTO_Member_Member_ID_I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid or Duplicate Data, Please Check..
        '''</summary>
        Friend ReadOnly Property Invalid_or_Duplicate_Data_Plea() As String
            Get
                Return ResourceManager.GetString("Invalid_or_Duplicate_Data_Plea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Investment.
        '''</summary>
        Friend ReadOnly Property Investment() As String
            Get
                Return ResourceManager.GetString("Investment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Name.
        '''</summary>
        Friend ReadOnly Property Last_Name() As String
            Get
                Return ResourceManager.GetString("Last_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Male.
        '''</summary>
        Friend ReadOnly Property Male() As String
            Get
                Return ResourceManager.GetString("Male", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Member.
        '''</summary>
        Friend ReadOnly Property Member() As String
            Get
                Return ResourceManager.GetString("Member", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Member ID and ID Card must be not blank..
        '''</summary>
        Friend ReadOnly Property Member_ID_and_ID_Card_must_be_() As String
            Get
                Return ResourceManager.GetString("Member_ID_and_ID_Card_must_be_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Member_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Member info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of shares.
        '''</summary>
        Friend ReadOnly Property Number_of_shares() As String
            Get
                Return ResourceManager.GetString("Number_of_shares", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fill Member ID for Delete..
        '''</summary>
        Friend ReadOnly Property Please_fill_Member_ID_for_Dele() As String
            Get
                Return ResourceManager.GetString("Please_fill_Member_ID_for_Dele", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fill Member ID for Update..
        '''</summary>
        Friend ReadOnly Property Please_fill_Member_ID_for_Upda() As String
            Get
                Return ResourceManager.GetString("Please_fill_Member_ID_for_Upda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;.
        '''</summary>
        Friend ReadOnly Property res() As String
            Get
                Return ResourceManager.GetString("res", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;, &apos;.
        '''</summary>
        Friend ReadOnly Property res0() As String
            Get
                Return ResourceManager.GetString("res0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;).
        '''</summary>
        Friend ReadOnly Property res1() As String
            Get
                Return ResourceManager.GetString("res1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %&apos; .
        '''</summary>
        Friend ReadOnly Property res2() As String
            Get
                Return ResourceManager.GetString("res2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %.
        '''</summary>
        Friend ReadOnly Property res3() As String
            Get
                Return ResourceManager.GetString("res3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *.
        '''</summary>
        Friend ReadOnly Property res4() As String
            Get
                Return ResourceManager.GetString("res4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Member.
        '''</summary>
        Friend ReadOnly Property SELECT_FROM_Member() As String
            Get
                Return ResourceManager.GetString("SELECT_FROM_Member", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Member WHERE [Member ID] = &apos;.
        '''</summary>
        Friend ReadOnly Property SELECT_FROM_Member_WHERE_Membe() As String
            Get
                Return ResourceManager.GetString("SELECT_FROM_Member_WHERE_Membe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Member WHERE [Member ID] LIKE &apos;%.
        '''</summary>
        Friend ReadOnly Property SELECT_FROM_Member_WHERE_Membe0() As String
            Get
                Return ResourceManager.GetString("SELECT_FROM_Member_WHERE_Membe0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Userlogin WHERE Username = &apos;.
        '''</summary>
        Friend ReadOnly Property SELECT_FROM_Userlogin_WHERE_Us() As String
            Get
                Return ResourceManager.GetString("SELECT_FROM_Userlogin_WHERE_Us", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success.
        '''</summary>
        Friend ReadOnly Property Success() As String
            Get
                Return ResourceManager.GetString("Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully Added.
        '''</summary>
        Friend ReadOnly Property Successfully_Added() As String
            Get
                Return ResourceManager.GetString("Successfully_Added", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully Deleted.
        '''</summary>
        Friend ReadOnly Property Successfully_Deleted() As String
            Get
                Return ResourceManager.GetString("Successfully_Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully Updated.
        '''</summary>
        Friend ReadOnly Property Successfully_Updated() As String
            Get
                Return ResourceManager.GetString("Successfully_Updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tel.
        '''</summary>
        Friend ReadOnly Property Tel() As String
            Get
                Return ResourceManager.GetString("Tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Member SET [ID Card] = &apos;.
        '''</summary>
        Friend ReadOnly Property UPDATE_Member_SET_ID_Card() As String
            Get
                Return ResourceManager.GetString("UPDATE_Member_SET_ID_Card", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username and Password Incorrect.
        '''</summary>
        Friend ReadOnly Property Username_and_Password_Incorrec() As String
            Get
                Return ResourceManager.GetString("Username_and_Password_Incorrec", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
